import "~/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";

import { TRPCReactProvider } from "~/trpc/react";
import AuthProvider from "./_components/nextAuthProvider";
export const metadata: Metadata = {
  title: "Notetaker",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${GeistSans.variable}`} data-theme="winter">
      <body>
        <TRPCReactProvider><AuthProvider>{children}</AuthProvider></TRPCReactProvider>
      </body>
    </html>
  );
}
